Na:KH KONTROL
Zn:KH KONTROL
Ar:tsk
Da: 5.10.2015
Kv:2
Kb:32
Uv:06.02.2015
Uv:TAB:012 564 KM
Uv:
Uv:
Uv:
Uv:Pravi proverka na EFB
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
Uv:
K2:    90.00
Ks:    10100
Kz:25
Eo:1
En:0
Co:31
Cn:9
Sc:0
Sn:0
Sp:0
Sl:0
D2:0
Dv:0
Do:XXXXXXX
Dt:0
Tr:0
Hs:0
Tt:1
El:0
Sf:1

St:#    1
V0:
T1:22
T2:23
X1:2
X2:3

St:#    2
V0:
T1:24
T2:25

Mc:A_PTC
Mn:5Q0972723A
Ml:20
Mf:21
Mz:3
Mx:
My:
Pb:0
Mp:0
SN:0

Mc:A_PTC_Klu4alka
Mn:5Q0972723A
Ml:0
Mf:24
Mz:2
Mx:
My:
Pb:0
Mp:0
SN:0

@
